[project]
name = "fotoblog-tests"
version = "0.1.0"
description = "Automated API and E2E tests for the Fotoblog application using Robot Framework, RequestsLibrary and SeleniumLibrary."
authors = [
    {name = "Tom K",email = "kasky@wp.pl"}
]
requires-python = ">=3.14,<4.0"
dependencies = [
    "robotframework (>=7.5,<8.0)",
    "robotframework-requests (>=0.9.7,<0.10.0)",
    "robotframework-seleniumlibrary (>=6.9.0,<7.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
