name: Automated Tests

on:
  push:
    branches: [ "master", "main", "features/API-tests", "robot-API-E2E-tests" ]

  pull_request:
    branches: [ "master", "main" ]

jobs:

  postman-api-tests:
    name: Postman API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Check Postman CLI
        run: postman --version

      - name: Run Postman Collection
        env:
          CI_VALID_USERNAME: ${{ secrets.VALID_USER_NAME }}
          CI_VALID_PASSWORD: ${{ secrets.VALID_USER_PASSWORD }}
        run: |
          postman collection run "./postman/collections/Fotoblog API" \
          -e ./postman/environments/PROD.environment.yaml \
          -d ./postman/data/auth_test_data.json \
          --env-var "validUsername=$CI_VALID_USERNAME" \
          --env-var "validPwd=$CI_VALID_PASSWORD" \
          --reporters cli


  robot-api-tests:
    name: Robot Framework API Tests
    runs-on: ubuntu-latest

    env:
      VALID_USER_NAME: ${{ secrets.VALID_USER_NAME }}
      VALID_USER_PASSWORD: ${{ secrets.VALID_USER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        working-directory: robot-tests
        run: poetry install

      - name: Run Robot Framework API tests
        working-directory: robot-tests
        run: poetry run robot --outputdir results tests/api

      - name: Upload Robot Framework results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-api-results
          path: robot-tests/results/


  robot-e2e-tests:
    name: Robot Framework E2E Tests
    runs-on: ubuntu-latest

    env:
      VALID_USER_NAME: ${{ secrets.VALID_USER_NAME }}
      VALID_USER_PASSWORD: ${{ secrets.VALID_USER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        working-directory: robot-tests
        run: poetry install

      - name: Run Robot Framework E2E tests
        working-directory: robot-tests
        run: poetry run robot --outputdir results tests/e2e

      - name: Upload Robot Framework results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-e2e-results
          path: robot-tests/results/